project:
  type: website

website:
  title: "PHYVIR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: mission.qmd
        text: Mission
    right:
      - href: https://www.nwo.nl/en/projects/afomm75533
        text: NWO
      - href: https://www.nioz.nl/en/news-and-blogs/news/nwo-science-xl-award-for-resolving-marine-phytoplankton-virus-interactions
        text: NIOZ
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "© 2026 PHYVIR Consortium"
    right: "[Impressum](impressum.qmd)"

format:
  html:
    theme: lux # flatly darkly
    toc: true
